// Automatisch generiert aus gym_app_funny_stats.json – 200 Sprüche in 4 Kategorien.
// Platzhalter: {weight} = Gesamtgewicht kg, {count} = Wiederholungen, {calories} = kcal.

export const FUNNY_SAYINGS: string[] = [
  "Du hast heute {weight} kg bewegt. Das entspricht dem Gewicht von ca. {count} ausgewachsenen Waschbären.",
  "Mit den heute verbrannten {calories} kcal könntest du eine klassische 60W-Glühbirne für {count} Stunden leuchten lassen.",
  "Dein heutiges Gesamtgewicht entspricht ungefähr {count} Kisten Bier, die du in den dritten Stock getragen hast.",
  "Die verbrannte Energie reicht aus, um das Smartphone eines Dauer-Scrollers für {count} Tage zu betreiben.",
  "Du hast heute die Masse von {count} durchschnittlichen Kleinwagen gestemmt.",
  "Deine Leistung auf dem Ergometer hätte ausgereicht, um ein Schlauchboot in {count} Sekunden prall aufzublasen.",
  "Du hast heute das Äquivalent von {count} Packungen Toilettenpapier aus der Hamsterkauf-Phase bewegt.",
  "Mit {calories} kcal hättest du einen handelsüblichen Handventilator für {count} Tage auf Stufe 3 betreiben können.",
  "Dein bewegtes Gewicht matcht sich heute mit der Masse von {count} vollbeladenen Einkaufswagen.",
  "Du hast heute das Gewicht von {count} Packungen Spaghetti bewegt. Kohlenhydrate muss man sich erarbeiten.",
  "Deine verbrannte Energie entspricht der Leistung, die man braucht, um {count} Liter Wasser zum Kochen zu bringen.",
  "Das heute bewegte Gewicht entspricht exakt {count} durchschnittlichen Weihnachtsbäumen.",
  "Du hast heute die Masse von {count} Ziegelsteinen bewegt. Du könntest theoretisch eine halbe Garage bauen.",
  "Deine verbrannten Kalorien könnten einen kleinen Kühlschrank für {count} Stunden kühlen.",
  "Du hast heute das Gewicht von {count} vollgepackten Urlaubsreisekoffern gehoben.",
  "Mit deiner Energie könnte man eine Mikrowelle für {count} Minuten auf höchster Stufe Popcorn machen lassen.",
  "Das bewegte Gewicht entspricht der Masse von {count} Gaming-PCs inklusive Monitor und RGB-Beleuchtung.",
  "Du hast heute das Äquivalent von {count} schweren Winterreifen bewegt.",
  "Deine verbrannten Kalorien reichen aus, um eine elektrische Zahnbürste {count} Monate zu betreiben.",
  "Du hast heute das Gesamtgewicht von {count} Sack Zement gestemmt.",
  "Mit der Energie hättest du einen Kaffee-Vollautomaten {count} Espresso ziehen lassen können.",
  "Du hast heute das Gewicht von {count} vollbesetzten Schlitten bewegt.",
  "Deine verbrannten {calories} kcal entsprechen der Standby-Energie eines Fernsehers für {count} Wochen.",
  "Du hast heute das Gewicht von {count} Golden Retrievern gehoben.",
  "Mit deiner Leistung könntest du eine Drohne für {count} Minuten in der Luft halten.",
  "Du hast heute das Gewicht von {count} Bowlingkugeln bewegt.",
  "Deine verbrannte Energie hätte eine Modelleisenbahn für {count} Stunden im Kreis fahren lassen.",
  "Du hast heute die Masse von {count} Aktenordnern voller Steuererklärungen gestemmt.",
  "Dein Kalorienverbrauch reicht aus, um eine Heißluftfritteuse für {count} Minuten zu betreiben.",
  "Du hast heute das Gewicht von {count} großen Werkzeugkoffern bewegt.",
  "Mit dieser Energie hättest du {count} Scheiben Toast perfekt bräunen können.",
  "Du hast heute das Äquivalent von {count} Mountainbikes gehoben.",
  "Deine verbrannten Kalorien könnten eine Gaming-Konsole für {count} Stunden unter Volllast versorgen.",
  "Du hast heute das Gewicht von {count} gefüllten Gießkannen bewegt.",
  "Mit dieser Leistung hättest du einen E-Scooter {count} Kilometer weit beschleunigen können.",
  "Du hast heute das Gewicht von {count} Autobatterien gestemmt.",
  "Deine verbrannte Energie entspricht dem Verbrauch eines WLAN-Verstärkers in {count} Tagen.",
  "Du hast heute das Gewicht von {count} massiven Holzstühlen bewegt.",
  "Mit den verbrannten {calories} kcal hättest du eine Musikbox auf maximaler Lautstärke für {count} Stunden betrieben.",
  "Du hast heute das Äquivalent von {count} Kaminholz-Säcken gehoben.",
  "Deine Energie hätte gereicht, um einen Saugroboter {count} Mal die gesamte Wohnung reinigen zu lassen.",
  "Du hast heute das Gewicht von {count} großen Kürbissen bewegt.",
  "Mit deinem Kalorienverbrauch hättest du einen Beamer für {count} Filme betreiben können.",
  "Du hast heute das Gewicht von {count} Autoreifen bewegt.",
  "Deine Energie hätte ein Aquarium für {count} Tage beheizt.",
  "Du hast heute das Äquivalent von {count} großen Lexika gestemmt.",
  "Mit den verbrannten Kalorien hättest du eine Lichterkette {count} Tage brennen lassen können.",
  "Du hast heute das Gewicht von {count} schweren Bratpfannen bewegt.",
  "Deine Leistung hätte gereicht, um einen Milchaufschäumer {count} Minuten am Stück zu betreiben.",
  "Du hast heute das Gesamtgewicht von {count} vollen Wassereimern gehoben.",
  "Du hast heute mehr Einsatz gezeigt als 94% der Leute, die sagen: 'Ich fange nächsten Montag an'.",
  "Du hast soeben die körperliche Aktivität von 12 Büroangestellten übertroffen, die einen Papierstau beheben.",
  "Du warst heute produktiver als 99% der Leute, die nur für ein Spiegel-Selfie ins Gym kommen.",
  "Während andere noch die perfekte Playlist suchen, hast du das Workout bereits erledigt.",
  "Du hast heute alle Couch-Potatos besiegt, die das Wetter als Ausrede genutzt haben.",
  "Du hast heute mehr Disziplin bewiesen als jeder, der 'nur noch eine Folge' auf Netflix schaut.",
  "Dein innerer Schweinehund liegt nach diesem Training winselnd in der Ecke.",
  "Du hast heute 95% der Menschen geschlagen, die Ausreden sammeln wie andere Briefmarken.",
  "Dein Einsatz war heute höher als der Puls von jemandem, der merkt, dass er den Herd angelassen hat.",
  "Du hast heute das Sofa-Vakuum erfolgreich durchbrochen.",
  "Während andere über Muskelaufbau philosophieren, hast du ihn einfach umgesetzt.",
  "Du hast heute die Ausrede 'Ich habe keine Zeit' offiziell für ungültig erklärt.",
  "Dein Training heute war härter als die Verhandlungen über den Abwasch zu Hause.",
  "Du hast heute mehr Bewegung gehabt als ein Durchschnitts-Gamer in einer ganzen Woche.",
  "Du hast heute das Getratsche an der Kaffeemaschine in echte Leistung umgemünzt.",
  "Dein heutiger Fokus war schärfer als das Messer des Dönerbuden-Besitzers deines Vertrauens.",
  "Du hast heute die Bequemlichkeit von 90% der Bevölkerung einfach übersprungen.",
  "Während andere den Aufzug genommen haben, hast du metaphorisch die Klippe erklommen.",
  "Du hast heute die Prokrastination eiskalt im Regen stehen lassen.",
  "Dein Workout hat heute mehr Willenskraft erfordert als das Ignorieren des Weckers am Montag.",
  "Du hast heute mehr geschafft als die Leute, die 'nur kurz' Social Media checken wollten.",
  "Deine Ausdauer heute war stabiler als die WLAN-Verbindung im ländlichen Raum.",
  "Du hast heute die 'Heute-nicht-Morgen-vielleicht'-Mentalität komplett zerstört.",
  "Du hast heute mehr bewegt als ein Umzugsunternehmen bei einem Single-Haushalt.",
  "Während die Welt pennt oder scrollt, ziehst du einfach durch.",
  "Du hast heute das Cardio-Level von jemandem erreicht, der den Bus noch knapp erwischt hat.",
  "Deine Disziplin heute war härter als die Kruste von zwei Tage altem Brot.",
  "Du hast heute das schlechte Gewissen der letzten Woche im Alleingang eliminiert.",
  "Du hast heute bewiesen, dass Ausreden bei dir keine Überlebenschance haben.",
  "Dein Workout war strukturierter als die meisten deutschen Behörden.",
  "Du hast heute die Trägheit besiegt. Physikalisch und mental.",
  "Während andere über Genetik jammern, baust du einfach Fakten auf.",
  "Du hast heute mehr Schweiß vergossen als ein Buchhalter bei einer Betriebsprüfung.",
  "Du hast heute das Fitnessstudio dominiert, während andere noch über die Parkplatzsuche fluchen.",
  "Dein innerer Kritiker hat heute Trainingsverbot bekommen.",
  "Du hast heute die Fraktion 'Ich gehe morgen laufen' deklassiert.",
  "Dein Einsatz heute war realer als die meisten Filter auf Instagram.",
  "Du hast heute die Bequemlichkeitszone nicht nur verlassen, sondern abgerissen.",
  "Während andere Proteinpulver vergleichen, hast du bereits die Muskeln dafür ermüdet.",
  "Du hast heute die Schrittkette von 5 Serienmarathon-Sitzern gesprengt.",
  "Dein Training war heute konsequenter als die Diät-Vorsätze an Silvester um 23:59 Uhr.",
  "Du hast heute mehr Energie gezeigt als ein Kleinkind nach drei Zuckerschocks.",
  "Du hast heute die Ausreden-Könige vom Thron gestoßen.",
  "Während andere die Hanteln nur anschauen, hast du sie verbogen.",
  "Du hast heute die Fraktion 'Das mache ich später' meilenweit hinter dir gelassen.",
  "Deine Leistung war heute unmissverständlicher als ein 'Nein' von der Türsteher-Legende.",
  "Du hast heute bewiesen, dass Motivation überbewertet und Disziplin der wahre MVP ist.",
  "Dein Workout hat heute die Trägheit des Universums ein Stück weit ausgeglichen.",
  "Du hast heute das Sofa-Monopol im Wohnzimmer erfolgreich boykottiert.",
  "Während andere noch zögern, hast du den Satz 'Ich zieh das jetzt durch' gelebt.",
  "In einem Paralleluniversum, in dem Schweiß die offizielle Währung ist, hättest du dir heute einen Gebrauchtwagen gekauft.",
  "Wären Muskelkater-Punkte an der Börse handelbar, hättest du heute einen eigenen Hedgefonds gegründet.",
  "In der Steinzeit hättest du mit der heutigen Leistung ein Mammut im Alleingang erlegt und ins Camp getragen.",
  "Wenn deine Muskelzellen Krypto-Miner wären, hättest du heute das gesamte Netzwerk lahmgelegt.",
  "In einem Universum, in dem Bizeps-Curls die Inflation ausgleichen, wärst du jetzt Großinvestor.",
  "Wenn Schweißtröpfchen Krypto-Coins wären, hättest du heute den Markt gecrasht.",
  "Auf dem Mars hättest du wegen der geringen Schwerkraft heute wahrscheinlich eine Raumstation angehoben.",
  "In einem RPG-Spiel hättest du mit diesem Workout gerade genug XP für das nächste epische Level-Up gesammelt.",
  "Wäre Trägheit ein Gegner in einem Kampfspiel, hättest du heute einen 'Flawless Victory' gelandet.",
  "In einer Welt, in der Energie direkt in WLAN-Signale umgewandelt wird, hättest du jetzt Highspeed-Internet im ganzen Viertel.",
  "Wenn Muskelmasse direkt proportionale politische Macht bedeuten würde, wärst du ab heute Bürgermeister.",
  "In einem Universum aus Gummi hättest du das Gym heute einmal komplett deformiert.",
  "Deine heutige Leistung hätte in der Antike gereicht, um als Halbgott durchzugehen.",
  "Wäre Schweiß flüssiges Gold, hättest du heute die Zentralbank ins Schwitzen gebracht.",
  "In einem Paralleluniversum, in dem Gewichte heben das Wetter steuert, hast du gerade einen perfekten Sommer heraufbeschworen.",
  "Wenn dein Körper ein Auto wäre, hättest du heute den Turbolader freigeschaltet.",
  "In der Welt der Ameisen wärst du nach diesem Workout der unbestrittene Herrscher des Planeten.",
  "Wenn Trainingsvolumen in Flugmeilen umgerechnet würde, hättest du jetzt ein Ticket nach Tokio.",
  "Wären deine Muskeln Solarpaneele, hättest du heute eine Kleinstadt mit Strom versorgt.",
  "In einem Paralleluniversum, in dem man durch Training schlauer wird, hättest du jetzt zwei Doktorstitel mehr.",
  "Wenn eisernes Training Stahl erzeugen würde, hättest du heute ein ganzes Kreuzfahrtschiff gegossen.",
  "In einer Welt ohne Schwerkraft wärst du heute bis zum Mond geflogen.",
  "Wäre dieses Workout ein Kinofilm, hätte er heute alle Kinokassen-Rekorde gebrochen.",
  "Wenn jede Wiederholung ein geschriebenes Wort wäre, hättest du heute einen Bestseller fertiggestellt.",
  "In einem Universum, in dem Fitnessstudios Tempel sind, bist du heute zum Hohepriester aufgestiegen.",
  "Wenn verbrannte Kalorien Bonuspunkte im Supermarkt wären, hättest du jetzt einen lebenslangen Vorrat an Snacks.",
  "In der Welt der Superhelden wäre das heute deine Origin-Story gewesen.",
  "Wäre deine Energie von heute Akkuladung, würde dein Laptop das nächste Jahrzehnt ohne Steckdose auskommen.",
  "In einem Paralleluniversum hast du heute durch das Gewichtheben die Erdrotation minimal beschleunigt.",
  "Wenn Muskelkater Applaus wäre, hättest du heute stehende Ovationen in einer ausverkauften Arena bekommen.",
  "In einer Welt, in der Disziplin sichtbar strahlt, bräuchtest du ab sofort eine Sonnenbrille im Spiegel.",
  "Wenn jede Hantelbewegung ein Klick wäre, wärst du jetzt viraler Trendsetter.",
  "In einem Universum, in dem Couch-Sitzen illegal ist, wärst du heute der oberste Verfassungsrichter.",
  "Wenn dein heutiger Fokus essbar wäre, wäre er schärfer als die schärfste Chili der Welt.",
  "Wäre das Gym eine Rennstrecke, hättest du heute die absolute Bestzeit in den Asphalt gebrannt.",
  "In der Welt der Roboter hätte man dir heute ein Software-Update für maximale Effizienz verpasst.",
  "Wenn jede Schweißperle ein Stern wäre, hättest du heute eine eigene Galaxie erschaffen.",
  "In einem Paralleluniversum hast du heute die Schwerkraft persönlich herausgefordert und gewonnen.",
  "Wäre dein Trainingsplan ein Gesetzestext, hättest du heute die Verfassung erfolgreich reformiert.",
  "Wenn das gehobene Gewicht in Kaffeebohnen gemessen würde, hättest du eine Plantage geerntet.",
  "In einer Welt, in der Willenskraft physische Berge versetzt, hättest du heute die Alpen ein Stück verschoben.",
  "Wenn deine Leistung heute ein Musikstück wäre, wäre es ein episches Heavy-Metal-Solo gewesen.",
  "In einem Universum, in dem Faulenzen wehtut, wärst du heute absolut schmerzfrei durch den Tag gekommen.",
  "Wenn jede Übung eine Aktie wäre, hättest du heute den DAX im Alleingang nach oben getrieben.",
  "Wäre dein Körper eine Festung, hättest du heute die Mauern massiv verstärkt.",
  "In der Welt der Spione hättest du heute die härteste Ausbildung ohne Wimpernzucken bestanden.",
  "Wenn dein Workout ein Treibstoff wäre, könnte eine Rakete damit die Stratosphäre durchbrechen.",
  "In einem Paralleluniversum hat dein heutiger Satz auf der Bank die Statik des Gebäudes verbessert.",
  "Wenn verbranntes Fett direkt in Konfetti umgewandelt würde, stündest du jetzt in einer riesigen Parade.",
  "In der Welt der Gladiatoren hättest du heute das Kolosseum als Champion verlassen.",
  "Deine Muskeln haben sich heute öfter angespannt als das Gesicht von jemandem, der in eine pure Zitrone beißt.",
  "Du hast heute genug Sauerstoff umgesetzt, um eine kleine Hüpfburg vollständig zu füllen.",
  "Dein Puls war heute zeitweise schneller als das Tippen eines Teenagers bei WhatsApp im Streitmodus.",
  "Deine Schweißdrüsen haben heute kurzzeitig die Jahresproduktion eines kleinen Mineralbrunnens übernommen.",
  "Dein Herz hat heute so zuverlässig geschlagen wie ein Schweizer Uhrwerk unter Extrembedingungen.",
  "Du hast heute so viele Nervenimpulse durch deinen Körper gejagt, dass man damit ein kleines Rechenzentrum hätte starten können.",
  "Deine Muskelfasern haben heute mehr Mikrorisse erlitten als das Display eines Smartphones ohne Schutzfolie nach einem Sturz.",
  "Dein Körper hat heute mehr Hitze produziert als die Serverräume eines mittelständischen Tech-Unternehmens.",
  "Deine Lungen haben heute mehr Luft gefiltert als die Klimaanlage eines vollbesetzten Großraumbüros im Hochsommer.",
  "Du hast heute so viele Endorphine ausgeschüttet, dass selbst ein mürrischer Beamter am Montag lächeln müsste.",
  "Deine Gelenke wurden heute besser geschmiert als die Kette eines Profi-Rennrads vor der Tour de France.",
  "Dein Bizeps war heute so prall aufgepumpt, dass deine T-Shirt-Ärmel kurz vor einer Dehnungsklage standen.",
  "Deine Beine haben heute mehr Arbeit geleistet als die Kolben eines alten Dieselmotors auf der Autobahn.",
  "Dein Blick beim letzten schweren Satz war fokussierter als der Laser eines Barcode-Scanners an der Supermarktkasse.",
  "Du hast heute so viel CO2 ausgeatmet, dass die Zimmerpflanzen in deinem Umkreis eine spontane Wachstumsparty feiern.",
  "Deine Durchblutung war heute so hoch, dass deine Adern das Straßennetz von Tokio nachgebildet haben.",
  "Deine Griffkraft war heute stabiler als die Halterung eines Action-Kamera-Saugnapfs an einem Rennwagen.",
  "Dein Körper hat heute mehr Energie umgesetzt als eine vollaktive Mikrowelle im Dauereinsatz.",
  "Deine Sehnen wurden heute härter auf die Probe gestellt als die Nerven von Eltern im dreistündigen Stau.",
  "Dein Herz-Kreislauf-System lief heute auf einem Drehzahlniveau, das jeden Sportwagen neidisch macht.",
  "Du hast heute beim Training so viel Fokus bewiesen, dass Fliegen in deiner Nähe freiwillig den Raum verlassen haben.",
  "Deine Oberschenkel haben heute mehr Druck ausgehalten als die Reifen eines vollbeladenen Lastwagens.",
  "Dein zentrales Nervensystem hat heute Signale schneller übertragen als Glasfaserkabel in der Innenstadt.",
  "Deine Schweißperlen hatten heute die Fließgeschwindigkeit eines Gebirgsbachs im Frühling.",
  "Deine Nackenmuskeln waren heute so angespannt wie die Stimmung vor der Zeugnisvergabe.",
  "Du hast heute so viel innere Hitze erzeugt, dass deine Brille beim Verlassen des Gyms beschlagen müsste.",
  "Deine Zellen haben heute ATP schneller verbrannt als ein Formel-1-Wagen den Treibstoff beim Qualifying.",
  "Dein Körper hat heute so effizient gearbeitet, dass Ingenieure dich gerne als Vorlage für eine Maschine hätten.",
  "Deine Waden haben heute mehr Stöße abgefedert als die Stoßdämpfer eines Offroad-Jeeps in der Wüste.",
  "Dein Gesichtsausdruck beim Workout hatte mehr Charakter als die meisten Hollywood-Schauspieler im gesamten Film.",
  "Deine Muskeln haben heute mehr Glykogen verbraucht als eine Bäckerei Mehl an einem Samstagmorgen.",
  "Dein Gleichgewichtssinn war heute schärfer als das Ortungssystem einer Fledermaus bei der Jagd.",
  "Deine Unterarme waren heute so hart, dass man darauf hätte trommeln können.",
  "Du hast heute so viel Sauerstoff durch dein Blut gejagt, dass deine Zellen wahrscheinlich eine Standing Ovation geben.",
  "Dein Puls hat heute Regionen erreicht, die sonst nur von Kolibris im Paarungsflug erforscht werden.",
  "Deine Schultern haben heute mehr Last getragen als der Server von Weltklasse-Spielen am Release-Tag.",
  "Dein Körper hat heute so stark entgiftet, dass du dich ab morgen praktisch als Bio-zertifiziert bezeichnen kannst.",
  "Deine Tiefenmuskulatur hat heute mehr Mikrobewegungen gemacht als ein Uhrmacher bei einer Luxusuhr.",
  "Deine Knie haben heute Belastungen standgehalten, die für die Statik mancher Brücken ausreichen würden.",
  "Dein Rücken war heute so stabil gebaut, dass man darauf eine Dachterrasse errichten könnte.",
  "Deine Schweißdrüsen liefen heute im absoluten Overdrive-Modus.",
  "Dein metabolischer Motor brennt nach diesem Training heißer als eine Sternschnuppe beim Eintritt in die Atmosphäre.",
  "Deine Füße haben heute mehr Grip auf dem Boden bewiesen als Neureifen auf frischem Asphalt.",
  "Deine Bauchmuskeln mussten heute mehr Kontraktionen durchstehen als ein Stand-up-Comedian Lachflashs hat.",
  "Dein Körper hat heute so viel Regeneration angestoßen, dass deine Zellen die Nachtschicht verdoppeln müssen.",
  "Deine Muskulatur war heute so aktiv, dass dein Grundumsatz für die nächsten 24 Stunden Achterbahn fährt.",
  "Dein Atemrhythmus beim Cardio hatte die Präzision einer industriellen Dampfmaschine.",
  "Deine Konzentration war heute so dicht, dass man sie fast hätte in Scheiben schneiden können.",
  "Deine Regeneration hat bereits begonnen, noch bevor du die Tasche gepackt hast – dein Körper fackelt nicht lange.",
  "Dein heutiger Trainingsreiz war so deutlich, dass deine Muskeln gar keine andere Wahl haben als zu wachsen.",
];

export function formatSaying(
  text: string,
  values: { weight: number; count: number; calories: number },
): string {
  return text
    .replaceAll("{weight}", Math.round(values.weight).toLocaleString("de-DE"))
    .replaceAll("{count}", String(Math.round(values.count)))
    .replaceAll("{calories}", String(Math.round(values.calories)));
}
